### ISSUE TITLE
[Bug]: This SqlTransaction has completed; it is no longer usable.

### ISSUE THREAD

**Issue by bbonkr** [bbonkr/AppleTv-Movie-Price-Tracker#48]
### Exception

Message: 
`This SqlTransaction has completed; it is no longer usable.`

Stack trace: 
```plaintext
   at Microsoft.Data.SqlClient.SqlTransaction.ZombieCheck()
   at Microsoft.Data.SqlClient.SqlTransaction.Rollback()
   at System.Data.Common.DbTransaction.RollbackAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.RollbackAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.RollbackAsync(CancellationToken cancellationToken)
   at AppleTv.Movie.Price.Tracker.Domains.Movies.Commands.TrackMovie.TrackMovieCommandHandler.Handle(TrackMovieCommand request, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Domains/Movies/Commands/TrackMovie/TrackMovieCommandHandler.cs:line 229
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at AppleTv.Movie.Price.Tracker.Jobs.MoviePriceCollectJob.ExecuteAsync(CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Jobs/MoviePriceCollectJob.cs:line 68
   at CronScheduler.Extensions.Internal.SchedulerHostedService.<>c__DisplayClass7_1.<<ExecuteOnceAsync>b__1>d.MoveNext() in C:\projects\cronscheduler-aspnetcore\src\CronScheduler.Extensions\Internal\SchedulerHostedService.cs:line 72
```

**Comment by bbonkr** [comment]
Host is busy
