### ISSUE TITLE
[Bug]: Resource temporarily unavailable (itunes.apple.com:443)

### ISSUE THREAD

**Issue by bbonkr** [bbonkr/AppleTv-Movie-Price-Tracker#49]
### Exception

Message: 
`Resource temporarily unavailable (itunes.apple.com:443)`

Stack trace: 
```plaintext
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at AppleTv.Movie.Price.Tracker.Services.ITunesSearchService.LookupMovieAsync(Int64 id, String storeCountry, String language, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Services/ITunesSearchService.cs:line 107
   at AppleTv.Movie.Price.Tracker.Domains.Movies.Queries.LookupMovie.LookupMovieQueryHandler.Handle(LookupMovieQuery request, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Domains/Movies/Queries/LookupMovie/LookupMovieQueryHandler.cs:line 29
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at AppleTv.Movie.Price.Tracker.Domains.Movies.Commands.TrackMovie.TrackMovieCommandHandler.Handle(TrackMovieCommand request, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Domains/Movies/Commands/TrackMovie/TrackMovieCommandHandler.cs:line 229
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at AppleTv.Movie.Price.Tracker.Jobs.MoviePriceCollectJob.ExecuteAsync(CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Jobs/MoviePriceCollectJob.cs:line 68
   at CronScheduler.Extensions.Internal.SchedulerHostedService.<>c__DisplayClass7_1.<<ExecuteOnceAsync>b__1>d.MoveNext() in C:\projects\cronscheduler-aspnetcore\src\CronScheduler.Extensions\Internal\SchedulerHostedService.cs:line 72
```

**Comment by bbonkr** [comment]
Host is busy
