### ISSUE TITLE
[Bug]: Service Unavailable

### ISSUE THREAD

**Issue by bbonkr** [bbonkr/AppleTv-Movie-Price-Tracker#58]
### Exception

Message: 
`Service Unavailable`

Stack trace: 
```plaintext
   at AppleTv.Movie.Price.Tracker.Services.ITunesSearchService.LookupMovieAsync(Int64 id, String storeCountry, String language, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Services/ITunesSearchService.cs:line 107
   at AppleTv.Movie.Price.Tracker.Domains.Movies.Queries.LookupMovie.LookupMovieQueryHandler.Handle(LookupMovieQuery request, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Domains/Movies/Queries/LookupMovie/LookupMovieQueryHandler.cs:line 29
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at AppleTv.Movie.Price.Tracker.Domains.Movies.Commands.TrackMovie.TrackMovieCommandHandler.Handle(TrackMovieCommand request, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Domains/Movies/Commands/TrackMovie/TrackMovieCommandHandler.cs:line 229
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at AppleTv.Movie.Price.Tracker.Jobs.MoviePriceCollectJob.ExecuteAsync(CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Jobs/MoviePriceCollectJob.cs:line 68
   at CronScheduler.Extensions.Internal.SchedulerHostedService.<>c__DisplayClass7_1.<<ExecuteOnceAsync>b__1>d.MoveNext() in C:\projects\cronscheduler-aspnetcore\src\CronScheduler.Extensions\Internal\SchedulerHostedService.cs:line 72
```

**Comment by bbonkr** [comment]
## Description

### Exception

Message: 
`Service Unavailable`

Stack trace: 
```plaintext
   at AppleTv.Movie.Price.Tracker.Services.ITunesSearchService.LookupMovieAsync(Int64 id, String storeCountry, String language, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Services/ITunesSearchService.cs:line 107
   at AppleTv.Movie.Price.Tracker.Domains.Movies.Queries.LookupMovie.LookupMovieQueryHandler.Handle(LookupMovieQuery request, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Domains/Movies/Queries/LookupMovie/LookupMovieQueryHandler.cs:line 29
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at AppleTv.Movie.Price.Tracker.Domains.Movies.Commands.TrackMovie.TrackMovieCommandHandler.Handle(TrackMovieCommand request, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Domains/Movies/Commands/TrackMovie/TrackMovieCommandHandler.cs:line 229
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at AppleTv.Movie.Price.Tracker.Jobs.MoviePriceCollectJob.ExecuteAsync(CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Jobs/MoviePriceCollectJob.cs:line 68
   at CronScheduler.Extensions.Internal.SchedulerHostedService.<>c__DisplayClass7_1.<<ExecuteOnceAsync>b__1>d.MoveNext() in C:\projects\cronscheduler-aspnetcore\src\CronScheduler.Extensions\Internal\SchedulerHostedService.cs:line 72
```

**Comment by bbonkr** [comment]
## Description

### Exception

Message: 
`Service Unavailable`

Stack trace: 
```plaintext
   at AppleTv.Movie.Price.Tracker.Services.ITunesSearchService.LookupMovieAsync(Int64 id, String storeCountry, String language, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Services/ITunesSearchService.cs:line 107
   at AppleTv.Movie.Price.Tracker.Domains.Movies.Queries.LookupMovie.LookupMovieQueryHandler.Handle(LookupMovieQuery request, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Domains/Movies/Queries/LookupMovie/LookupMovieQueryHandler.cs:line 29
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at AppleTv.Movie.Price.Tracker.Domains.Movies.Commands.TrackMovie.TrackMovieCommandHandler.Handle(TrackMovieCommand request, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Domains/Movies/Commands/TrackMovie/TrackMovieCommandHandler.cs:line 229
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 54
   at AppleTv.Movie.Price.Tracker.Jobs.MoviePriceCollectJob.ExecuteAsync(CancellationToken cancellationToken) in /app/src/AppleTv.Movie.Price.Tracker.Jobs/MoviePriceCollectJob.cs:line 68
   at CronScheduler.Extensions.Internal.SchedulerHostedService.<>c__DisplayClass7_1.<<ExecuteOnceAsync>b__1>d.MoveNext() in C:\projects\cronscheduler-aspnetcore\src\CronScheduler.Extensions\Internal\SchedulerHostedService.cs:line 72
```

**Comment by bbonkr** [comment]
## Description

### Exception

Message: 
`Service Unavailable`

Stack trace: 
```plaintext
   at AppleTv.Movie.Price.Tracker.Services.ITunesSearchService.LookupMovieAsync(Int64 id, String storeCountry, String language, CancellationToken cancellationToken) in /Users/bbon/Repos/appletv-movie-price-tracker/src/AppleTv.Movie.Price.Tracker.Services/ITunesSearchService.cs:line 105
   at AppleTv.Movie.Price.Tracker.Domains.Movies.Queries.LookupMovie.LookupMovieQueryHandler.Handle(LookupMovieQuery request, CancellationToken cancellationToken) in /Users/bbon/Repos/appletv-movie-price-tracker/src/AppleTv.Movie.Price.Tracker.Domains/Movies/Queries/LookupMovie/LookupMovieQueryHandler.cs:line 21
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /Users/bbon/Repos/appletv-movie-price-tracker/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 23
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /Users/bbon/Repos/appletv-movie-price-tracker/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 23
   at AppleTv.Movie.Price.Tracker.Domains.Movies.Commands.TrackMovie.TrackMovieCommandHandler.Handle(TrackMovieCommand request, CancellationToken cancellationToken) in /Users/bbon/Repos/appletv-movie-price-tracker/src/AppleTv.Movie.Price.Tracker.Domains/Movies/Commands/TrackMovie/TrackMovieCommandHandler.cs:line 35
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /Users/bbon/Repos/appletv-movie-price-tracker/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 23
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at AppleTv.Movie.Price.Tracker.App.Infrastructure.Validations.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /Users/bbon/Repos/appletv-movie-price-tracker/src/AppleTv.Movie.Price.Tracker.App/Infrastructure/Validations/ValidationBehavior.cs:line 23
   at AppleTv.Movie.Price.Tracker.Jobs.MoviePriceCollectJob.ExecuteAsync(CancellationToken cancellationToken) in /Users/bbon/Repos/appletv-movie-price-tracker/src/AppleTv.Movie.Price.Tracker.Jobs/MoviePriceCollectJob.cs:line 51
   at CronScheduler.Extensions.Internal.SchedulerHostedService.<>c__DisplayClass7_1.<<ExecuteOnceAsync>b__1>d.MoveNext() in C:\projects\cronscheduler-aspnetcore\src\CronScheduler.Extensions\Internal\SchedulerHostedService.cs:line 58
```
